---
# Houssam's Personal Freqtrade Docker Configuration
# Secure setup with environment variables and Redis integration

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    container_name: houssam_freqtrade_redis
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - freqtrade-network

  freqtrade:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: houssam_freqtrade_bot
    env_file:
      - .env
    environment:
      - PYTHONPATH=/freqtrade/user_data/scripts
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - redis
    networks:
      - freqtrade-network
    # Default command - trading mode
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json

networks:
  freqtrade-network:
    driver: bridge

volumes:
  redis_data:
